//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preparate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Preparate()
        {
            this.Comanda_Preparat = new HashSet<Comanda_Preparat>();
            this.Alergenis = new HashSet<Alergeni>();
            this.Pozes = new HashSet<Poze>();
        }
    
        public int id_preparat { get; set; }
        public string denumire { get; set; }
        public Nullable<double> pret { get; set; }
        public Nullable<int> cantintate_portie { get; set; }
        public Nullable<int> cantitate_restaurant { get; set; }
        public Nullable<int> id_categorie { get; set; }
    
        public virtual Categorii Categorii { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comanda_Preparat> Comanda_Preparat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alergeni> Alergenis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Poze> Pozes { get; set; }
    }
}
