//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pret_Comenzi
    {
        public int id_pretComanda { get; set; }
        public Nullable<int> id_comanda { get; set; }
        public Nullable<double> pret { get; set; }
    
        public virtual Comenzi Comenzi { get; set; }
    }
}
